services:
  frontend:
    build:
      context: .
      args:
        VITE_ENV: production
        VITE_LOG_LEVEL: info
        VITE_GATEWAY_URL: https://api.hyglobalcopcu.com
        VITE_UMAMI_SCRIPT_URL: placeHolder
        VITE_UMAMI_WEBSITE_ID: placeHolder
    container_name: hy-globalcopcu-frontend
    ports:
      - '8080:80'
    restart: always
